typography_spectrum: 0.4845729705411941
color:
  brandStrength: 0.8287269659340382
  lightness: 0.9565863905008882
  saturation: 0.24794752220623195
  rhythmicContrast: 0.6225202966015786
  brandColors:
    - '#9A9BA0'
    - '#455757'
    - '#08080A'
    - '#FEFEFE'
    - '#D0C4B7'
layout_spectrum: 0.894479607231915
name: stevelong.co
title: "\"Steve has a different and radical coaching aproach\"\_"
description: >-
  If you are really serious about your life and personal performance, if you are
  really at the point where you want to climb the ladders of success, you really
  need a guy like Steve to temporarily help you climb the first few steps.
  -Active PGA player
